
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: student_management_system
    restart: always
#    command: sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8000" # uncomment this on production
    command: python manage.py runserver 0.0.0.0:8000 # comment this on production
    volumes:
      - ./:/code/
    expose:
      - 8000
#    ports:
#      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery_worker
      - celery_beat
      - celery_flower
  celery_worker:
    build: .
    container_name: student_management_system_celery_worker
    command: celery -A core worker -l info
    restart: always
    volumes:
      - ./:/code/
    depends_on:
      - redis
      - db
  celery_beat:
    build: .
    container_name: student_management_system_celery_beat
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    volumes:
      - ./:/code/
    depends_on:
      - redis
      - db
  celery_flower:
    build: .
    container_name: student_management_system_celery_flower
    command: celery -A core --broker="${BROKER_URL}" flower --basic_auth=${flower_username}:${flower_password}
    restart: always
    env_file:
      - .env
    ports:
      - 5559:5555
    depends_on:
      - redis
    volumes:
      - ./:/code/
  nginx:
    build: ./nginx
    container_name: student_management_system_nginx
    restart: always
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    ports:
      - 8003:80
    depends_on:
      - web
  db:
    image: postgres:17.6-alpine
    container_name: student_management_system_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - student_management_system_data:/var/lib/postgresql/data
  redis:
    image: redis:8.0-alpine
    container_name: student_management_system_redis
    restart: always
    volumes:
      - ./redish/data/:/data/
      - ./redish/log/:/var/log/redis
volumes:
  student_management_system_data:
