name: Pylint Code Quality Checker

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Pylint Code Quality Checker
      env:
        DEBUG: True
        SECRET_KEY: dummy
        ALLOWED_HOSTS: localhost,127.0.0.1
        CSRF_TRUSTED_ORIGINS: http://localhost:5010
        ALLOWED_ORIGINS: http://localhost:5010
        DB_ENGINE: django.db.backends.postgresql
        DB_NAME: forest_project
        DB_USER: forest_project
        DB_PASSWORD: db_password
        DB_HOST: db
        DB_PORT: 5432
        BROKER_URL: redis://redis:6379/0
        CELERY_RESULT_BACKEND: redis://redis:6379/0
      run: |
        DJANGO_SETTINGS_MODULE=core.settings pylint --load-plugins=pylint_django .
